### ISSUE TITLE
CannotPullContainerError: Error response from daemon: manifest for  not found

### ISSUE THREAD

**Issue by advissor** [CircleCI-Public/circleci-demo-aws-ecs-ecr#4]
I tried to build a project from master branch.
Terraform part - successful
Circle CI part - successfull in GUI
Though, when I go to ECS console and check tasks > they are continuosly failing with error :

`CannotPullContainerError: Error response from daemon: manifest for nginx:0f6b3cdf5e24f0da3dd932acd84fd90e9786a522 not found`

Tried to reproduce this with ECR locally on my own server and same error was in case I try to perform docker run with image which docker can't find locally
So, at the end after modifying to :
` docker run -it --name ccitt1 8xxxxxxxxxxxxxxx.dkr.ecr.us-xxxx-x.amazonaws.com/cci:0f6b3cdf5e24f0da3dd932acd84fd90e9786a522 /bin/sh`

I was able to run it
No files from repo were modified other than terraform + project setting modified in gui + workflow itself is succesfull

I guess task definition is made under the hood in build & deploy? Or this is something specific to ECS/Fargate?
Last time master was built 1 month ago

**Update1:**
Within task definition in ECS, i see in json following :
```
"stopTimeout": null,
      "image": "nginx:0f6b3cdf5e24f0da3dd932acd84fd90e9786a522",
      "startTimeout": null,
```
I think this is an issue, as naming for image should be AWS specific and not nginx to be build properly by fargate . Found couple other people on web having same error because of invalid tag. Failed to Pull container error (400) from ECR API 
**Update2:**
In GUI, checked configuration for workflow (**deploy-service-update**) :
**PREVIOUS_TASK_DEFINITION**=$(aws ecs describe-task-definition --task-definition ${AWS_RESOURCE_NAME_PREFIX}-service)
**CONTAINER_IMAGE_NAME_UPDATES**="$(echo container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1})"

Provided terraform script builds task with nginx by default.
So, maybe this is not coincidense and some transformation error in workflow within **lines 172 - 213** 

Thanks ,
Vladyslav

**Comment by lokst** [comment]
Hi @advissor Thank you for reporting this, I'll investigate it!

**Comment by advissor** [comment]
Hi @lokst ,
Thanks for a fix & added verification steps after deployment!
Build was successful!

*note: might be useful for someone. Had to do terraform destroy +  apply , to make it working. Otherwise, terraform could not update the port of ECS > ELB health check was failing , containers being stopped.

**Comment by ozooxo** [comment]
Hi @lokst ,
Not sure if you also want to update the `simple_orb_demo` branch. The orb repo is still refer to that branch (although I don't understand the difference between the two branches).

https://github.com/CircleCI-Public/aws-ecs-orb/blame/bbb70497205d75862a486b0d2167161a50e25c0e/README.MD#L11

**Comment by lokst** [comment]
Hi @ozooxo , thanks for pointing that out! The 2 branches should be the same (the reason there are 2 is mainly historical and we may remove it going forward), I've pushed the changes to the `simple_orb_demo` branch
